package com.peng.shop.business.goods.entity;

import java.io.Serializable;

public class GoodsEntity implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.goods_id
     *
     * @mbg.generated Sat Nov 14 17:45:49 CST 2020
     */
    private Long goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.goods_desc
     *
     * @mbg.generated Sat Nov 14 17:45:49 CST 2020
     */
    private String goodsDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.goods_text
     *
     * @mbg.generated Sat Nov 14 17:45:49 CST 2020
     */
    private String goodsText;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.goods_icon
     *
     * @mbg.generated Sat Nov 14 17:45:49 CST 2020
     */
    private String goodsIcon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.goods_image
     *
     * @mbg.generated Sat Nov 14 17:45:49 CST 2020
     */
    private String goodsImage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.goods_price
     *
     * @mbg.generated Sat Nov 14 17:45:49 CST 2020
     */
    private String goodsPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.goods_num
     *
     * @mbg.generated Sat Nov 14 17:45:49 CST 2020
     */
    private Long goodsNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.fist_category
     *
     * @mbg.generated Sat Nov 14 17:45:49 CST 2020
     */
    private Short fistCategory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.second_category
     *
     * @mbg.generated Sat Nov 14 17:45:49 CST 2020
     */
    private Short secondCategory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.goods_type
     *
     * @mbg.generated Sat Nov 14 17:45:49 CST 2020
     */
    private Integer goodsType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.activity_id
     *
     * @mbg.generated Sat Nov 14 17:45:49 CST 2020
     */
    private Long activityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table goods
     *
     * @mbg.generated Sat Nov 14 17:45:49 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.goods_id
     *
     * @return the value of goods.goods_id
     *
     * @mbg.generated Sat Nov 14 17:45:49 CST 2020
     */
    public Long getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.goods_id
     *
     * @param goodsId the value for goods.goods_id
     *
     * @mbg.generated Sat Nov 14 17:45:49 CST 2020
     */
    public void setGoodsId(Long goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.goods_desc
     *
     * @return the value of goods.goods_desc
     *
     * @mbg.generated Sat Nov 14 17:45:49 CST 2020
     */
    public String getGoodsDesc() {
        return goodsDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.goods_desc
     *
     * @param goodsDesc the value for goods.goods_desc
     *
     * @mbg.generated Sat Nov 14 17:45:49 CST 2020
     */
    public void setGoodsDesc(String goodsDesc) {
        this.goodsDesc = goodsDesc == null ? null : goodsDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.goods_text
     *
     * @return the value of goods.goods_text
     *
     * @mbg.generated Sat Nov 14 17:45:49 CST 2020
     */
    public String getGoodsText() {
        return goodsText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.goods_text
     *
     * @param goodsText the value for goods.goods_text
     *
     * @mbg.generated Sat Nov 14 17:45:49 CST 2020
     */
    public void setGoodsText(String goodsText) {
        this.goodsText = goodsText == null ? null : goodsText.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.goods_icon
     *
     * @return the value of goods.goods_icon
     *
     * @mbg.generated Sat Nov 14 17:45:49 CST 2020
     */
    public String getGoodsIcon() {
        return goodsIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.goods_icon
     *
     * @param goodsIcon the value for goods.goods_icon
     *
     * @mbg.generated Sat Nov 14 17:45:49 CST 2020
     */
    public void setGoodsIcon(String goodsIcon) {
        this.goodsIcon = goodsIcon == null ? null : goodsIcon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.goods_image
     *
     * @return the value of goods.goods_image
     *
     * @mbg.generated Sat Nov 14 17:45:49 CST 2020
     */
    public String getGoodsImage() {
        return goodsImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.goods_image
     *
     * @param goodsImage the value for goods.goods_image
     *
     * @mbg.generated Sat Nov 14 17:45:49 CST 2020
     */
    public void setGoodsImage(String goodsImage) {
        this.goodsImage = goodsImage == null ? null : goodsImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.goods_price
     *
     * @return the value of goods.goods_price
     *
     * @mbg.generated Sat Nov 14 17:45:49 CST 2020
     */
    public String getGoodsPrice() {
        return goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.goods_price
     *
     * @param goodsPrice the value for goods.goods_price
     *
     * @mbg.generated Sat Nov 14 17:45:49 CST 2020
     */
    public void setGoodsPrice(String goodsPrice) {
        this.goodsPrice = goodsPrice == null ? null : goodsPrice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.goods_num
     *
     * @return the value of goods.goods_num
     *
     * @mbg.generated Sat Nov 14 17:45:49 CST 2020
     */
    public Long getGoodsNum() {
        return goodsNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.goods_num
     *
     * @param goodsNum the value for goods.goods_num
     *
     * @mbg.generated Sat Nov 14 17:45:49 CST 2020
     */
    public void setGoodsNum(Long goodsNum) {
        this.goodsNum = goodsNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.fist_category
     *
     * @return the value of goods.fist_category
     *
     * @mbg.generated Sat Nov 14 17:45:49 CST 2020
     */
    public Short getFistCategory() {
        return fistCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.fist_category
     *
     * @param fistCategory the value for goods.fist_category
     *
     * @mbg.generated Sat Nov 14 17:45:49 CST 2020
     */
    public void setFistCategory(Short fistCategory) {
        this.fistCategory = fistCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.second_category
     *
     * @return the value of goods.second_category
     *
     * @mbg.generated Sat Nov 14 17:45:49 CST 2020
     */
    public Short getSecondCategory() {
        return secondCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.second_category
     *
     * @param secondCategory the value for goods.second_category
     *
     * @mbg.generated Sat Nov 14 17:45:49 CST 2020
     */
    public void setSecondCategory(Short secondCategory) {
        this.secondCategory = secondCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.goods_type
     *
     * @return the value of goods.goods_type
     *
     * @mbg.generated Sat Nov 14 17:45:49 CST 2020
     */
    public Integer getGoodsType() {
        return goodsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.goods_type
     *
     * @param goodsType the value for goods.goods_type
     *
     * @mbg.generated Sat Nov 14 17:45:49 CST 2020
     */
    public void setGoodsType(Integer goodsType) {
        this.goodsType = goodsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.activity_id
     *
     * @return the value of goods.activity_id
     *
     * @mbg.generated Sat Nov 14 17:45:49 CST 2020
     */
    public Long getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.activity_id
     *
     * @param activityId the value for goods.activity_id
     *
     * @mbg.generated Sat Nov 14 17:45:49 CST 2020
     */
    public void setActivityId(Long activityId) {
        this.activityId = activityId;
    }
}