package com.peng.shop.business.temp.dao;

import com.peng.shop.business.temp.model.TempModel;
import com.peng.shop.business.temp.model.TempModelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TempModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temp
     *
     * @mbg.generated Wed Nov 11 22:12:40 CST 2020
     */
    long countByExample(TempModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temp
     *
     * @mbg.generated Wed Nov 11 22:12:40 CST 2020
     */
    int deleteByExample(TempModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temp
     *
     * @mbg.generated Wed Nov 11 22:12:40 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temp
     *
     * @mbg.generated Wed Nov 11 22:12:40 CST 2020
     */
    int insert(TempModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temp
     *
     * @mbg.generated Wed Nov 11 22:12:40 CST 2020
     */
    int insertSelective(TempModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temp
     *
     * @mbg.generated Wed Nov 11 22:12:40 CST 2020
     */
    List<TempModel> selectByExample(TempModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temp
     *
     * @mbg.generated Wed Nov 11 22:12:40 CST 2020
     */
    TempModel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temp
     *
     * @mbg.generated Wed Nov 11 22:12:40 CST 2020
     */
    int updateByExampleSelective(@Param("record") TempModel record, @Param("example") TempModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temp
     *
     * @mbg.generated Wed Nov 11 22:12:40 CST 2020
     */
    int updateByExample(@Param("record") TempModel record, @Param("example") TempModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temp
     *
     * @mbg.generated Wed Nov 11 22:12:40 CST 2020
     */
    int updateByPrimaryKeySelective(TempModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temp
     *
     * @mbg.generated Wed Nov 11 22:12:40 CST 2020
     */
    int updateByPrimaryKey(TempModel record);
}