package com.peng.shop.business.temp.dao;

import com.peng.shop.business.temp.entity.TempEntity;
import com.peng.shop.business.temp.entity.TempEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TempEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temp
     *
     * @mbg.generated Sat Nov 14 12:31:29 CST 2020
     */
    long countByExample(TempEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temp
     *
     * @mbg.generated Sat Nov 14 12:31:29 CST 2020
     */
    int deleteByExample(TempEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temp
     *
     * @mbg.generated Sat Nov 14 12:31:29 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temp
     *
     * @mbg.generated Sat Nov 14 12:31:29 CST 2020
     */
    int insert(TempEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temp
     *
     * @mbg.generated Sat Nov 14 12:31:29 CST 2020
     */
    int insertSelective(TempEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temp
     *
     * @mbg.generated Sat Nov 14 12:31:29 CST 2020
     */
    List<TempEntity> selectByExample(TempEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temp
     *
     * @mbg.generated Sat Nov 14 12:31:29 CST 2020
     */
    TempEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temp
     *
     * @mbg.generated Sat Nov 14 12:31:29 CST 2020
     */
    int updateByExampleSelective(@Param("record") TempEntity record, @Param("example") TempEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temp
     *
     * @mbg.generated Sat Nov 14 12:31:29 CST 2020
     */
    int updateByExample(@Param("record") TempEntity record, @Param("example") TempEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temp
     *
     * @mbg.generated Sat Nov 14 12:31:29 CST 2020
     */
    int updateByPrimaryKeySelective(TempEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temp
     *
     * @mbg.generated Sat Nov 14 12:31:29 CST 2020
     */
    int updateByPrimaryKey(TempEntity record);
}